#!/usr/bin/env bash
#
# Woven Model Licensing Server — Deployment Script (Linux/Mac)
# ============================================================
set -euo pipefail

# Colors using tput
BOLD=$(tput bold 2>/dev/null || echo "")
RED=$(tput setaf 1 2>/dev/null || echo "")
GREEN=$(tput setaf 2 2>/dev/null || echo "")
YELLOW=$(tput setaf 3 2>/dev/null || echo "")
CYAN=$(tput setaf 6 2>/dev/null || echo "")
WHITE=$(tput setaf 7 2>/dev/null || echo "")
NC=$(tput sgr0 2>/dev/null || echo "")

# ── Helper functions ──────────────────────────────────────────
info()  { printf "${CYAN}%s${NC}\n" "$*"; }
ok()    { printf "${GREEN}  [OK] %s${NC}\n" "$*"; }
warn()  { printf "${YELLOW}  [WARN] %s${NC}\n" "$*"; }
error() { printf "${RED}  [ERROR] %s${NC}\n" "$*"; }
step()  { printf "\n${YELLOW}[%s] %s${NC}\n" "$1" "$2"; }

# ── Header ────────────────────────────────────────────────────
clear
printf "${BOLD}${CYAN}"
printf "============================================\n"
printf "  Woven Model Licensing Server — Deployment\n"
printf "============================================\n"
printf "${NC}\n"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${SCRIPT_DIR}/../licensing-server"

# ── Step 1: Check prerequisites ────────────────────────────────
step "1/6" "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
    error "Docker is not installed!"
    printf "\n${YELLOW}Manual install instructions:${NC}\n"
    printf "  Visit https://www.docker.com/products/docker-desktop/\n"
    printf "  Or use your package manager:\n"
    printf "    Ubuntu/Debian: sudo apt install docker.io\n"
    printf "    macOS: brew install --cask docker\n"
    printf "    Fedora: sudo dnf install docker\n"
    printf "\nOnce installed, re-run this script.\n"
    exit 1
fi
ok "Docker found"

DOCKER_COMPOSE="docker-compose"
if ! command -v "$DOCKER_COMPOSE" &>/dev/null; then
    if docker compose version &>/dev/null; then
        DOCKER_COMPOSE="docker compose"
        ok "Docker Compose plugin found"
    else
        error "Docker Compose is not available!"
        printf "${YELLOW}  Install Docker Compose: https://docs.docker.com/compose/install/${NC}\n"
        exit 1
    fi
else
    ok "docker-compose found"
fi

if ! command -v python3 &>/dev/null && ! command -v python &>/dev/null; then
    error "Python 3 is required but not found!"
    printf "${YELLOW}  Install Python 3 from https://www.python.org/downloads/${NC}\n"
    exit 1
fi
PYTHON="python3"
if ! command -v "$PYTHON" &>/dev/null; then
    PYTHON="python"
fi
ok "Python found ($($PYTHON --version 2>&1))"

# ── Step 2: Check environment ──────────────────────────────────
step "2/6" "Checking environment configuration..."

if [ ! -f "$PROJECT_DIR/.env.production" ]; then
    if [ -f "$PROJECT_DIR/.env.production.example" ]; then
        warn ".env.production not found, copying from example..."
        cp "$PROJECT_DIR/.env.production.example" "$PROJECT_DIR/.env.production"
        ok "Created .env.production from example"
    else
        warn "No .env.production.example found. Creating minimal .env.production..."
        cat > "$PROJECT_DIR/.env.production" <<-EOF
# Woven Model Licensing Server — Production Configuration
# Generated by deploy.sh on $(date)

# Database
DATABASE_URL=sqlite:///./woven_licensing.db

# Server
HOST=0.0.0.0
PORT=8000

# Security
SECRET_KEY=change-this-to-a-random-secret-key
ADMIN_EMAIL=admin@wovenmodel.com
ADMIN_PASSWORD=admin

# Signing Keys (generated by generate_keys.py)
SIGNING_PRIVATE_KEY=
SIGNING_PUBLIC_KEY=
EOF
        ok "Created minimal .env.production"
    fi
else
    ok ".env.production exists"
fi

# Source the environment file
set -a
source "$PROJECT_DIR/.env.production"
set +a

# ── Step 3: Signing keys ───────────────────────────────────────
step "3/6" "Checking signing keys..."

NEED_KEYS=false
if [ -z "${SIGNING_PRIVATE_KEY:-}" ] || [ -z "${SIGNING_PUBLIC_KEY:-}" ]; then
    NEED_KEYS=true
fi

if [ "$NEED_KEYS" = true ]; then
    warn "Signing keys not set."
    if [ -f "$PROJECT_DIR/generate_keys.py" ]; then
        $PYTHON "$PROJECT_DIR/generate_keys.py"
        if [ $? -eq 0 ]; then
            # Re-source to get the new keys
            set -a
            source "$PROJECT_DIR/.env.production"
            set +a
            ok "Keys generated successfully"
        else
            error "Failed to generate keys"
            exit 1
        fi
    else
        error "generate_keys.py not found at $PROJECT_DIR/generate_keys.py"
        exit 1
    fi
else
    ok "Signing keys are set"
fi

# ── Step 4: Domain / SSL ──────────────────────────────────────
step "4/6" "Domain name configuration..."

DOMAIN_NAME=""
printf "${CYAN}  Enter domain name for SSL (leave blank for localhost):${NC} "
read -r DOMAIN_NAME

if [ -z "$DOMAIN_NAME" ]; then
    DOMAIN_NAME="localhost"
    warn "Using localhost — SSL will not be configured"
else
    info "Domain set to: $DOMAIN_NAME"
    # Write DOMAIN to .env.production
    if grep -q "^DOMAIN=" "$PROJECT_DIR/.env.production" 2>/dev/null; then
        sed -i.bak "s|^DOMAIN=.*|DOMAIN=$DOMAIN_NAME|" "$PROJECT_DIR/.env.production"
    else
        echo "DOMAIN=$DOMAIN_NAME" >> "$PROJECT_DIR/.env.production"
    fi
    ok "Domain written to .env.production"
fi

# ── Step 4b: SSL setup with certbot (optional) ────────────────
DO_SSL=false
if [ "$DOMAIN_NAME" != "localhost" ]; then
    printf "\n${CYAN}  Do you want to set up SSL with Let's Encrypt (certbot)? [y/N]:${NC} "
    read -r SSL_ANSWER
    case "$SSL_ANSWER" in
        y|Y|yes|YES) DO_SSL=true ;;
    esac

    if [ "$DO_SSL" = true ]; then
        if ! command -v certbot &>/dev/null; then
            warn "certbot not found. Attempting to install..."
            if command -v apt-get &>/dev/null; then
                sudo apt-get update && sudo apt-get install -y certbot
            elif command -v brew &>/dev/null; then
                brew install certbot
            elif command -v dnf &>/dev/null; then
                sudo dnf install -y certbot
            else
                error "Cannot install certbot automatically."
                printf "${YELLOW}  Install manually: https://certbot.eff.org/instructions${NC}\n"
                DO_SSL=false
            fi
        fi

        if [ "$DO_SSL" = true ]; then
            step "4.1/6" "Obtaining SSL certificate..."
            sudo certbot certonly --standalone -d "$DOMAIN_NAME" --non-interactive --agree-tos -m "jude@wovenmodel.com" || true
            ok "SSL certificate obtained (or attempted)"
        fi
    fi
fi

# ── Step 5: Start services ─────────────────────────────────────
step "5/6" "Starting services..."

cd "$PROJECT_DIR"
$DOCKER_COMPOSE up -d
if [ $? -ne 0 ]; then
    error "Failed to start Docker services"
    exit 1
fi
ok "Services started successfully"

# ── Step 6: Seed admin ─────────────────────────────────────────
step "6/6" "Running seed script..."

cd "$SCRIPT_DIR"
$PYTHON seed_admin.py
if [ $? -eq 0 ]; then
    ok "Admin user seeded"
else
    warn "Seed script had issues (non-critical)"
fi

# ── Success output ─────────────────────────────────────────────
printf "\n${BOLD}${GREEN}"
printf "============================================\n"
printf "  Deployment Complete!\n"
printf "============================================${NC}\n"
printf "\n"
info "  Licensing Server:"
printf "    http://localhost:8000\n"
printf "\n"
info "  API Documentation:"
printf "    http://localhost:8000/docs\n"
printf "\n"
if [ "$DOMAIN_NAME" != "localhost" ]; then
    info "  Management Portal:"
    printf "    https://%s:8000\n" "$DOMAIN_NAME"
    printf "\n"
    if [ "$DO_SSL" = true ]; then
        info "  SSL configured with Let's Encrypt"
    else
        info "  SSL Certificates:"
        printf "    Run certbot manually if needed:\n"
        printf "    sudo certbot --nginx -d %s\n" "$DOMAIN_NAME"
    fi
else
    info "  Management Portal:"
    printf "    http://localhost:8000/admin\n"
fi
printf "\n"
printf "${YELLOW}  Next Steps:${NC}\n"
printf "    1. Open the API docs to explore endpoints\n"
printf "    2. Use license_cli.py to manage licenses:\n"
printf "       python license_cli.py list\n"
printf "       python license_cli.py generate --product STRATUM --user 1 --type perpetual\n"
printf "    3. Run create_test_license.py to generate test licenses:\n"
printf "       python create_test_license.py --email admin@wovenmodel.com --password admin\n"
printf "    4. Configure your applications with the license server URL\n"
printf "\n"
info "  Support: jude@wovenmodel.com"
printf "\n"